# Node Docker Image Ref ---------------------------------
# https://hub.docker.com/_/node?tab=description
# -------------------------------------------------------

stages:
    - test
    - release
    - deploy

# TEST STAGE --------------------------------------------
# Audit the code base and run unit tests
# -------------------------------------------------------
code_validation:
    stage: test
    image: node:16.8-buster
    script:
        - npm install
        # - npm audit fix
        - npm run prettier
        - npm run compile
        - npm run lint
        - npm run test
    coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
    tags:
        - gcp

# RELEASE STAGE -----------------------------------------
# Version up and trigger the release
# Docs: https://juhani.gitlab.io/go-semrel-gitlab/
# -------------------------------------------------------
release:
    stage: release
    image: registry.gitlab.com/juhani/go-semrel-gitlab:v0.20.4
    script:
        - release next-version --bump-patch
        - release tag
        - release changelog
    when: on_success
    only:
        refs:
            - master
    except:
        variables:
            - $CI_COMMIT_MESSAGE =~ /.*\[bump-version\]/
    tags:
        - gcp

# DEVELOPMENT DEPLOY STAGE ------------------------------
# Push the "develop" build to the GCP bucket
# -------------------------------------------------------
deploy_development:
    stage: deploy
    image: node:16.8-buster
    before_script:
        - curl -sSL https://sdk.cloud.google.com | bash
        - . ~/google-cloud-sdk/path.bash.inc
    script:
        - apt-get update && apt-get install -y python-pip
        - npm install
        # - npm audit fix
        - npm run build-dev
        - gcloud config set project aa-payload-dev
        - gsutil rm gs://${GCP_DEVELOPMENT_BUCKET_NAME}/**
        - gsutil mv dist/** gs://${GCP_DEVELOPMENT_BUCKET_NAME}
        - gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}
        - gcloud compute url-maps invalidate-cdn-cache payload-dev --host ${GCP_DEVELOPMENT_CDN_NAME} --path "/*"
    only:
        refs:
            - develop
    tags:
        - gcp

# STAGING DEPLOY STAGE ------------------------------
# Push the "staging" build to the GCP bucket
# -------------------------------------------------------
deploy_staging:
    stage: deploy
    image: node:16.8-buster
    before_script:
        - curl -sSL https://sdk.cloud.google.com | bash
        - . ~/google-cloud-sdk/path.bash.inc
    script:
        - apt-get update && apt-get install -y python-pip
        - npm install
        # - npm audit fix
        - npm run build-stg
        - gcloud config set project aa-payload-stg
        - gsutil rm gs://${GCP_STAGING_BUCKET_NAME}/**
        - gsutil mv dist/** gs://${GCP_STAGING_BUCKET_NAME}
        - gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}
        - gcloud compute url-maps invalidate-cdn-cache payload-stg --host ${GCP_STAGING_CDN_NAME} --path "/*"
    only:
        refs:
            - staging
    tags:
        - gcp

# PRODUCTION DEPLOY STAGE ------------------------------
# Push the "production" build to the GCP bucket
# -------------------------------------------------------
deploy_master:
    stage: deploy
    image: node:16.8-buster
    before_script:
        - curl -sSL https://sdk.cloud.google.com | bash
        - . ~/google-cloud-sdk/path.bash.inc
    script:
        - apt-get update && apt-get install -y python-pip
        - npm install
        # - npm audit fix
        - npm run build-prod
        - gcloud config set project aa-payload-pro
        - gsutil cp dist/** gs://${GCP_ARCHIVE_BUCKET_NAME}/payloads/$CI_COMMIT_TAG
        - gsutil rm gs://${GCP_PRODUCTION_BUCKET_NAME}/**
        - gsutil mv dist/** gs://${GCP_PRODUCTION_BUCKET_NAME}
        - gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}
        - gcloud compute url-maps invalidate-cdn-cache payload-pro --host ${GCP_PRODUCTION_CDN_NAME} --path "/*"
    only:
        - tags
    tags:
        - gcp
